### PR TITLE
Put now waits 5 seconds for status to appear

### PR DESCRIPTION
**Pull request by SHyx0rmZ**

### CODE REVIEW

**Comment by dpb587** [comment]
Looks great. Anything magical about 5 seconds?

**Comment by SHyx0rmZ** [comment]
Not really, it just keeps the `out/simple` test short.

**Comment by SHyx0rmZ** [comment]
If you have a different suggestion, I'm glad to hear it.

**Comment by dpb587** [comment]
Thanks!

**Comment by SHyx0rmZ** [comment]
Thanks for merging it!

**Pull request merged**
